version: "3.9"

services:
  userdb:
    image: mongo:6.0
    container_name: userdb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongo-data-user:/data/db

  salesdb:
    image: mongo:6.0
    container_name: salesdb
    ports:
      - "27018:27017"  # Farklı portta çalışacak
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongo-data-sales:/data/db

  clientdb:
    image: mongo:6.0
    container_name: clientdb
    ports:
      - "27019:27017"  # Farklı portta çalışacak
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongo-data-client:/data/db
  
  userservice:
    build:
      context: ./UserService 
    container_name: userservice
    environment:
      MONGO_URI: mongodb://admin:adminpassword@userdb:27017/userdb?authSource=admin
      JWT_SECRET: 123asd123
      GATEWAY_SECRET_KEY: 123secretTunnel456
    ports:
      - "5001:5001" 
    depends_on:
      - userdb

  salesservice:
      build:
        context: ./SalesService 
      container_name: salesservice
      environment:
        MONGO_URI: mongodb://admin:adminpassword@salesdb:27017/salesdb?authSource=admin
        JWT_SECRET: 123asd123
        GATEWAY_SECRET_KEY: 123secretTunnel456
      ports:
        - "5002:5002" 
      depends_on:
        - salesdb 

  clientservice:
    build:
      context: ./ClientService 
    container_name: clientservice
    environment:
      MONGO_URI: mongodb://admin:adminpassword@clientdb:27017/clientdb?authSource=admin
      JWT_SECRET: 123asd123
      GATEWAY_SECRET_KEY: 123secretTunnel456
    ports:
      - "5003:5003" 
    depends_on:
      - clientdb
  
  apigateway:
    build: 
      context: ./Gateway
    container_name: apigateway
    environment:
      USER_SERVICE_URL: http://localhost:5001
      SALE_SERVICE_URL: http://localhost:5002
      CLIENT_SERVICE_URL: http://localhost:5003
      JWT_SECRET: 123asd123
      GATEWAY_SECRET_KEY: 123secretTunnel456
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - userservice
      - clientservice
      - salesservice

    

volumes:
  mongo-data-user:
    driver: local

  mongo-data-sales:
    driver: local

  mongo-data-client:
    driver: local
