version: "3.9"

services:
  userdb:
    image: mongo:6.0
    container_name: userdb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongo-data-user:/data/db

  salesdb:
    image: mongo:6.0
    container_name: salesdb
    ports:
      - "27018:27017"  # Farklı portta çalışacak
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongo-data-sales:/data/db

  clientdb:
    image: mongo:6.0
    container_name: clientdb
    ports:
      - "27019:27017"  # Farklı portta çalışacak
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongo-data-client:/data/db
  
  userservice:
    build:
      context: ./UserService 
    container_name: userservice
    environment:
      MONGO_URI: mongodb://admin:adminpassword@userdb:27017/userdb?authSource=admin
      JWT_SECRET: 123asd123
      GATEWAY_SECRET_KEY: 123secretTunnel456
    ports:
      - "5000:5000" 
    depends_on:
      - userdb

  salesservice:
      build:
        context: ./SalesService 
      container_name: salesservice
      environment:
        MONGO_URI: mongodb://admin:adminpassword@salesdb:27017/salesdb?authSource=admin
        JWT_SECRET: 123asd123
        GATEWAY_SECRET_KEY: 123secretTunnel456
      ports:
        - "5002:5000" 
      depends_on:
        - salesdb 

  clientservice:
    build:
      context: ./ClientService 
    container_name: clientservice
    environment:
      MONGO_URI: mongodb://admin:adminpassword@clientdb:27017/clientdb?authSource=admin
      JWT_SECRET: 123asd123
      GATEWAY_SECRET_KEY: 123secretTunnel456
    ports:
      - "5001:5000" 
    depends_on:
      - clientdb 

    

volumes:
  mongo-data-user:
    driver: local

  mongo-data-sales:
    driver: local

  mongo-data-client:
    driver: local
